"""T071–T073: challenge scoping/economics + portfolio aggregation + S5 verification."""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

import challenge  # noqa: E402
import portfolio_aggregate  # noqa: E402


# --- T071: challenge scoping ---------------------------------------------------

def test_incremental_scope_only_changed_artifacts():
    artifacts = {"a.md": "hash1", "b.md": "hash2", "c.md": "hash3"}
    since = {"a.md": "hash1", "b.md": "hashX"}  # c is new, b changed, a unchanged
    assert challenge.incremental_scope(artifacts, since) == ["b.md", "c.md"]


def test_backstops_fire_on_semantic_events():
    assert challenge.backstop_trigger(1, False, False) == []
    assert challenge.backstop_trigger(10, False, False) == ["periodic_full_sweep"]
    assert challenge.backstop_trigger(1, True, False) == ["constitution_bump"]
    assert challenge.backstop_trigger(1, False, True) == ["subscription_change"]


def test_lifecycle_hooks_at_decision_moments():
    assert challenge.lifecycle_hook("pillar_complete")
    assert challenge.lifecycle_hook("thesis_complete")
    assert challenge.lifecycle_hook("pre_reduction")
    assert not challenge.lifecycle_hook("random_moment")


def test_finding_cap_severity_sorted_with_overflow_summary():
    findings = [challenge.make_finding("NVDA", "m", "2026Q2", "contradicts", "low")
                for _ in range(60)]
    findings[0]["severity"] = "high"
    kept, overflow = challenge.cap_findings(findings)
    assert len(kept) == challenge.MAX_FINDINGS
    assert kept[0]["severity"] == "high"
    assert overflow["dropped"] == 10
    assert "contradicts:low" in overflow["overflow_summary"]


def test_challenge_ids_stable_across_runs():
    a = challenge.make_finding("NVDA", "gross_margin", "2026Q2", "contradicts")
    b = challenge.make_finding("NVDA", "gross_margin", "2026Q2", "contradicts")
    assert a["id"] == b["id"]


# --- T072: portfolio aggregation ----------------------------------------------

def _workspace(tmp_path, rows):
    ws = tmp_path / "workspace"
    for tid, claims in rows.items():
        thesis = ws / "theses" / tid
        thesis.mkdir(parents=True)
        (thesis / "thesis.md").write_text(json.dumps(
            {"judgment": {"claims": claims, "conviction": 0.8}}))
    return ws


def test_conflicts_listed_never_adjudicated(tmp_path):
    ws = _workspace(tmp_path, {
        "001-bull": [{"id": "c-1", "entity": "NVDA", "state": "pinned",
                      "direction": "long", "position_pct": 4.0, "sector": "semis"}],
        "002-bear": [{"id": "c-2", "entity": "NVDA", "state": "pinned",
                      "direction": "short", "position_pct": 2.0, "sector": "semis"}],
    })
    agg = portfolio_aggregate.aggregate(portfolio_aggregate.scan_active_claims(ws))
    assert agg["conflicts"], agg
    assert agg["conflicts"][0]["ticker"] == "NVDA"
    # adjudication is NOT automated: the aggregator has no state-change output
    assert "retired" not in json.dumps(agg)


def test_pending_review_and_retired_excluded(tmp_path):
    ws = _workspace(tmp_path, {
        "001-a": [{"id": "c-1", "entity": "NVDA", "state": "pinned",
                   "direction": "long", "position_pct": 4.0, "sector": "semis"},
                  {"id": "c-2", "entity": "NVDA", "state": "pending_review",
                   "direction": "long", "position_pct": 9.0, "sector": "semis"}],
    })
    agg = portfolio_aggregate.aggregate(portfolio_aggregate.scan_active_claims(ws))
    assert agg["by_ticker"]["NVDA"]["weighted"] == round(4.0 * 0.8, 2)


def test_conviction_weighted_ticker_aggregation(tmp_path):
    ws = _workspace(tmp_path, {
        "001-a": [{"id": "c-1", "entity": "NVDA", "state": "pinned",
                   "direction": "long", "position_pct": 4.0, "sector": "semis"}],
        "001-b": [{"id": "c-2", "entity": "NVDA", "state": "pinned",
                   "direction": "long", "position_pct": 2.0, "sector": "semis"}],
    })
    agg = portfolio_aggregate.aggregate(portfolio_aggregate.scan_active_claims(ws))
    assert agg["by_ticker"]["NVDA"]["weighted"] == round(6.0 * 0.8, 2)


def test_views_render_and_emit(tmp_path):
    ws = _workspace(tmp_path, {
        "001-a": [{"id": "c-1", "entity": "NVDA", "state": "pinned",
                   "direction": "long", "position_pct": 4.0, "sector": "semis"}]})
    agg = portfolio_aggregate.aggregate(portfolio_aggregate.scan_active_claims(ws))
    view = portfolio_aggregate.render(agg)
    assert view.startswith("<!-- GENERATED by portfolio_aggregate.py")
    conflicts = portfolio_aggregate.render_conflicts(agg)
    assert "IC agenda input" in conflicts
