#!/usr/bin/env python3
"""portfolio_aggregate.py — the derived portfolio view (spec 046 Q61).

Q4/Q16 "derive, never ledger" applied at workspace scale: the portfolio view is
RECOMPUTED on every run from thesis claims + artifact frontmatter — a persisted
portfolio file would silently diverge from the theses that produced it.

Pipeline: scan active claims (exclude pending_review/retired) → conviction-weighted
ticker aggregation with divergence flags → sector aggregation with Q16 aggregate
gates → emit `_portfolio/portfolio-view.md` (derived) + `_portfolio/conflicts.md`
(IC agenda input). Adjudication is Q66 `retired_by_ic` — NEVER automated.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))
import g1_gate  # noqa: E402

ACTIVE_STATES = {"pinned", "stale_price"}  # pending_review / retired excluded (Q61)


def scan_active_claims(workspace: Path) -> list[dict[str, Any]]:
    """Read every thesis.md judgment claim + its artifact positions."""
    rows: list[dict[str, Any]] = []
    theses_dir = workspace / "theses"
    if not theses_dir.is_dir():
        return rows
    for thesis_dir in sorted(theses_dir.iterdir()):
        thesis_md = thesis_dir / "thesis.md"
        if not thesis_md.is_file():
            continue
        try:
            doc = json.loads(thesis_md.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            continue
        conviction = doc.get("judgment", {}).get("conviction") or 0.5
        for claim in (doc.get("judgment") or {}).get("claims") or []:
            if not isinstance(claim, dict):
                continue
            if claim.get("state") not in ACTIVE_STATES:
                continue
            # direction + position from the claim or its artifacts
            direction = claim.get("direction", "long")
            pos = claim.get("position_pct")
            if pos is None:
                for art in sorted((thesis_dir / "artifacts").rglob("*.md")):
                    fm = g1_gate.parse_frontmatter(art.read_text(encoding="utf-8"))
                    if isinstance(fm.get("position_pct"), (int, float)):
                        pos = float(fm["position_pct"])
                        break
            rows.append({"thesis_id": thesis_dir.name, "claim_id": claim.get("id"),
                         "ticker": claim.get("entity"), "direction": direction,
                         "position_pct": float(pos) if pos is not None else 0.0,
                         "sector": claim.get("sector", "unspecified"),
                         "conviction": float(conviction)})
    return rows


def aggregate(rows: list[dict[str, Any]]) -> dict[str, Any]:
    """Conviction-weighted ticker aggregation with divergence flags + sector sums."""
    by_ticker: dict[str, dict[str, Any]] = {}
    for r in rows:
        t = r["ticker"]
        if t not in by_ticker:
            by_ticker[t] = {"directions": set(), "weighted": 0.0, "sector": r["sector"]}
        by_ticker[t]["directions"].add(r["direction"])
        by_ticker[t]["weighted"] += r["position_pct"] * r["conviction"]
    sectors: dict[str, float] = {}
    for t, agg in by_ticker.items():
        sectors[agg["sector"]] = sectors.get(agg["sector"], 0.0) + agg["weighted"]
    conflicts = [{"ticker": t, "directions": sorted(a["directions"])}
                 for t, a in by_ticker.items() if len(a["directions"]) > 1]
    return {"by_ticker": {t: {"weighted": round(a["weighted"], 2),
                              "sector": a["sector"]} for t, a in by_ticker.items()},
            "by_sector": {s: round(v, 2) for s, v in sectors.items()},
            "conflicts": conflicts}


def render(agg: dict[str, Any]) -> str:
    lines = ["<!-- GENERATED by portfolio_aggregate.py — derived; regenerate to update -->", "",
             "## Portfolio View (derived)", "", "| ticker | conviction-weighted position | sector |",
             "|---|---|---|"]
    for t, a in sorted(agg["by_ticker"].items()):
        lines.append(f"| {t} | {a['weighted']}% | {a['sector']} |")
    lines += ["", "## Sector aggregation", "", "| sector | total |", "|---|---|"]
    for s, v in sorted(agg["by_sector"].items()):
        lines.append(f"| {s} | {v}% |")
    return "\n".join(lines) + "\n"


def render_conflicts(agg: dict[str, Any]) -> str:
    lines = ["# Cross-thesis conflicts — IC agenda input", ""]
    if not agg["conflicts"]:
        lines.append("(none)")
    for c in agg["conflicts"]:
        lines.append(f"- {c['ticker']}: opposite directions "
                     f"({' vs '.join(c['directions'])}) — adjudicate via Q66 retired_by_ic")
    return "\n".join(lines) + "\n"


def _atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(".tmp")
    tmp.write_text(content, encoding="utf-8")
    with open(tmp, "rb") as f:
        os.fsync(f.fileno())
    os.replace(tmp, path)


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="Derived portfolio view (Q61)")
    p.add_argument("--workspace", required=True)
    args = p.parse_args(argv)
    agg = aggregate(scan_active_claims(Path(args.workspace)))
    _atomic_write(Path(args.workspace) / "_portfolio" / "portfolio-view.md", render(agg))
    _atomic_write(Path(args.workspace) / "_portfolio" / "conflicts.md", render_conflicts(agg))
    print(f"portfolio-view.md + conflicts.md emitted — {len(agg['conflicts'])} conflict(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
