#!/usr/bin/env python3
"""thesis_status.py — the derived thesis index, invocation name `agentii.status`
(spec 046 Q75). NOT an 8th kit skill: status is pure derivation, and a derivation
must not become a skill (Q4 ledger trap).

Scans theses/*/thesis.md frontmatter and emits:
  - a human-readable summary (active theses, ticker coverage, pin states,
    known-open count, pending_review count)
  - theses/INDEX.md — a GENERATED file (DO NOT EDIT header); CI (Check 34)
    proves it regenerates byte-identically.

No cache: the scan is frontmatter-only; caching lands only if measured (Q20's rule).
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))
import g1_gate  # noqa: E402 — shared frontmatter parser

INDEX_HEADER = "<!-- GENERATED by agentii.status — DO NOT EDIT -->\n"

THESIS_RE = __import__("re").compile(r"^(\d{3})-[a-z0-9-]+$")


def scan_workspace(workspace: Path) -> list[dict[str, Any]]:
    theses_dir = workspace / "theses"
    rows: list[dict[str, Any]] = []
    if not theses_dir.is_dir():
        return rows
    for thesis_dir in sorted(theses_dir.iterdir()):
        if not thesis_dir.is_dir() or not THESIS_RE.match(thesis_dir.name):
            continue
        thesis_md = thesis_dir / "thesis.md"
        if not thesis_md.is_file():
            rows.append({"id": thesis_dir.name, "present": False})
            continue
        fm = g1_gate.parse_frontmatter(thesis_md.read_text(encoding="utf-8"))
        pins = {p: fm.get(p) for p in g1_gate.FIVE_PINS}
        # derived ticker coverage: subscriptions + entity_claims entities
        tickers: set[str] = set()
        for sub in fm.get("subscriptions") or []:
            for t in __import__("re").findall(r"\b[A-Z0-9]{1,5}\b", str(sub)):
                tickers.add(t)
        for c in fm.get("entity_claims") or []:
            if isinstance(c, dict) and c.get("entity"):
                tickers.add(str(c["entity"]))
        pending = 0
        try:
            doc = json.loads(thesis_md.read_text(encoding="utf-8"))
            for claim in (doc.get("judgment") or {}).get("claims") or []:
                if isinstance(claim, dict) and claim.get("state") == "pending_review":
                    pending += 1
        except (ValueError, AttributeError):
            pass
        rows.append({
            "id": thesis_dir.name,
            "present": True,
            "pins": pins,
            "tickers": sorted(tickers),
            "known_open": len(fm.get("known-open") or []),
            "pending_review": pending,
            "budget": fm.get("budget"),
        })
    return rows


def pending_gates(row: dict[str, Any], thesis_dir: Path) -> list[str]:
    """Q80: gates never time out into approval — pending_gate claims age and are
    surfaced here; blocking is observable, never silent. Waiting past the
    threshold becomes a converge finding (Q80)."""
    import datetime

    out: list[str] = []
    thesis_md = thesis_dir / "thesis.md"
    if not thesis_md.is_file():
        return out
    try:
        doc = json.loads(thesis_md.read_text(encoding="utf-8"))
    except (ValueError, AttributeError):
        return out
    now = datetime.datetime.now(datetime.timezone.utc)
    for claim in (doc.get("judgment") or {}).get("claims") or []:
        if isinstance(claim, dict) and claim.get("state") == "pending_gate":
            since = claim.get("gate_since")
            age = ""
            if since:
                try:
                    dt = datetime.datetime.fromisoformat(str(since))
                    age_days = (now - dt).days
                    age = f" (waiting {age_days}d)"
                except ValueError:
                    pass
            out.append(f"pending_gate: {claim.get('id')}{age}")
    return out


def render_index(rows: list[dict[str, Any]]) -> str:
    lines = [INDEX_HEADER.rstrip(), "",
             "| thesis | present | tickers | known-open | pending_review |",
             "|---|---|---|---|---|"]
    for r in rows:
        tickers = ",".join(r.get("tickers") or [])
        lines.append(f"| {r['id']} | {'yes' if r.get('present') else 'NO — thesis.md missing'} "
                     f"| {tickers} | {r.get('known_open', 0)} | {r.get('pending_review', 0)} |")
    return "\n".join(lines) + "\n"


def _atomic_write(path: Path, content: str) -> None:
    tmp = path.with_suffix(".tmp")
    tmp.write_text(content, encoding="utf-8")
    with open(tmp, "rb") as f:
        os.fsync(f.fileno())
    os.replace(tmp, path)


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="Derived thesis index + INDEX.md emit (Q75)")
    p.add_argument("--workspace", required=True)
    p.add_argument("--json", action="store_true")
    args = p.parse_args(argv)
    rows = scan_workspace(Path(args.workspace))
    if args.json:
        print(json.dumps(rows, indent=2))
    else:
        print(render_index(rows), end="")
        _atomic_write(Path(args.workspace) / "theses" / "INDEX.md", render_index(rows))
        print(f"\n(INDEX.md emitted — {len(rows)} theses)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
